<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - Run on Headless Edge</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>Run on Headless Edge</h1>
<p>
  Test duration: 489.636s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">ProjectEnas.UserRegister_Step2_Membership</td>
      </tr>
            
<tr>
  <td class="method">
                  CA203_04_Check_Input_InValid
      </td>
  <td class="duration">
    4.546s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1の最小文字数文字以上255の最大文字数文字以下でご入力ください。] but found []</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:453)<br />
              org.testng.Assert.assertEquals(Assert.java:463)<br />
              ProjectEnas.UserRegister_Step2_Membership.CA203_04_Check_Input_InValid(UserRegister_Step2_Membership.java:125)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.base/java.lang.reflect.Method.invoke(Method.java:566)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  CA203_05_Check_Input_Valid
      </td>
  <td class="duration">
    105.488s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (3):<br/>
Failure 1 of 3<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA203_05_Check_Input_Valid(UserRegister_Step2_Membership.java:159)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 2 of 3<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA203_05_Check_Input_Valid(UserRegister_Step2_Membership.java:184)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 3 of 3<br/>
java.lang.AssertionError: expected [true] but found [false]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertTrue(Assert.java:44)<br />
              org.testng.Assert.assertTrue(Assert.java:54)<br />
              commons.BaseTest.verifyTrue(BaseTest.java:160)<br />
              ProjectEnas.UserRegister_Step2_Membership.CA203_05_Check_Input_Valid(UserRegister_Step2_Membership.java:186)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.base/java.lang.reflect.Method.invoke(Method.java:566)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  CA204_04_Check_Action_Success
      </td>
  <td class="duration">
    89.427s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Multiple failures (12):<br/>
Failure 1 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:282)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 2 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:284)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 3 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:286)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 4 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:288)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 5 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:290)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 6 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:292)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 7 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:294)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 8 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:296)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 9 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:298)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 10 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:300)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 11 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:96)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:776)<br/>
	at org.testng.Assert.assertTrue(Assert.java:44)<br/>
	at org.testng.Assert.assertTrue(Assert.java:54)<br/>
	at commons.BaseTest.verifyTrue(BaseTest.java:160)<br/>
	at ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:303)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:648)<br/>
	at org.testng.TestRunner.run(TestRunner.java:505)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br/>
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br/>
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br/>
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)<br/>
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br/>
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br/>
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br/>
	at org.testng.TestNG.runSuites(TestNG.java:1049)<br/>
	at org.testng.TestNG.run(TestNG.java:1017)<br/>
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br/>
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br/>
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br/>
<br/>
Failure 12 of 12<br/>
java.lang.AssertionError: expected [true] but found [false]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertTrue(Assert.java:44)<br />
              org.testng.Assert.assertTrue(Assert.java:54)<br />
              commons.BaseTest.verifyTrue(BaseTest.java:160)<br />
              ProjectEnas.UserRegister_Step2_Membership.CA204_04_Check_Action_Success(UserRegister_Step2_Membership.java:305)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.base/java.lang.reflect.Method.invoke(Method.java:566)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
      </table>


  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">ProjectEnas.UserLogin</td>
      </tr>
            
<tr>
  <td class="method">
                  CA000_01_CheckUI
      </td>
  <td class="duration">
    0.819s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA000_02_Check_TextLink
      </td>
  <td class="duration">
    2.293s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA000_03_Email_Blank
      </td>
  <td class="duration">
    0.476s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA000_04_Password_Blank
      </td>
  <td class="duration">
    0.411s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA000_05_Email_InValid
      </td>
  <td class="duration">
    1.599s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA000_06_Password_InValid
      </td>
  <td class="duration">
    0.967s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA000_07_Login_Success
      </td>
  <td class="duration">
    6.425s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">ProjectEnas.UserRegister_Step1_SendEmail</td>
      </tr>
            
<tr>
  <td class="method">
                  CA200_01__CheckUI
      </td>
  <td class="duration">
    1.001s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA200_02_CheckTextLink
      </td>
  <td class="duration">
    5.266s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_04_CheckUI
      </td>
  <td class="duration">
    4.809s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_05_Check_Input_Blank
      </td>
  <td class="duration">
    5.182s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_06_Check_Name_Valid
      </td>
  <td class="duration">
    10.423s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_07_Check_Name_InValid
      </td>
  <td class="duration">
    0.939s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_08_Check_Email_Valid
      </td>
  <td class="duration">
    21.236s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_09_Check_Email_InValid
      </td>
  <td class="duration">
    2.142s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_10_Check_Password_Valid
      </td>
  <td class="duration">
    31.136s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_11_Check_Password_InValid
      </td>
  <td class="duration">
    9.898s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA201_12_Check_Email_Exist
      </td>
  <td class="duration">
    1.327s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">ProjectEnas.UserRegister_Step2_Membership</td>
      </tr>
            
<tr>
  <td class="method">
                  CA202_01_Check_Success
      </td>
  <td class="duration">
    1.361s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA203_01_Login_Site_Third
      </td>
  <td class="duration">
    57.521s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA203_02_Check_UI
      </td>
  <td class="duration">
    0.853s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA203_03_Check_Input_Blank
      </td>
  <td class="duration">
    0.824s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA204_01_Check_UI
      </td>
  <td class="duration">
    0.725s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA204_02_Check_Input_Blank
      </td>
  <td class="duration">
    7.770s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA204_03_Check_Input_Vaild
      </td>
  <td class="duration">
    6.525s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">ProjectEnas.UserRestPW</td>
      </tr>
            
<tr>
  <td class="method">
                  CA300_01_Check_UI
      </td>
  <td class="duration">
    1.024s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA300_02_Email_Blank
      </td>
  <td class="duration">
    0.167s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA300_03_Email_Wrong_Format
      </td>
  <td class="duration">
    0.951s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA300_04_Email_Invalid
      </td>
  <td class="duration">
    0.364s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA300_05_Email_Success
      </td>
  <td class="duration">
    10.384s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA302_01_Check_Mail
      </td>
  <td class="duration">
    56.209s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA302_02_Check_UI
      </td>
  <td class="duration">
    0.538s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA302_03_PW_BLANK
      </td>
  <td class="duration">
    0.200s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA_302_04_PW_Less_8_32
      </td>
  <td class="duration">
    0.355s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA_302_05_PW_Wrong
      </td>
  <td class="duration">
    1.095s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA_302_06_ConfirmPW_No_Duplicate
      </td>
  <td class="duration">
    0.331s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA_302_07_Rest_PW_Success
      </td>
  <td class="duration">
    3.143s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  CA_302_08_Login_NewPW
      </td>
  <td class="duration">
    6.790s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
      </table>
  
</body>
</html>
